language: scala
env:
  - ACTIVATOR_VERSION=1.2.10
before_script:
  - wget http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
  - unzip -q typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip
script: typesafe-activator-${ACTIVATOR_VERSION}-minimal/activator -Dconfig.file=conf/travis-ci.conf test
